app/models.py
from flask_login import UserMixin

from app import db, login_manager


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(128), nullable=False, unique=True)
    login = db.Column(db.String(128), nullable=False)
    password = db.Column(db.String(128), nullable=False)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/forms.py
from flask_wtf import FlaskForm, RecaptchaField, Recaptcha
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import InputRequired, Email, Length


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(message='Неправильный формат!'), Length(max=50)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=80)])
    remember = BooleanField('Remember me')
    recaptcha = RecaptchaField(validators=[Recaptcha(message='Please complete the captcha')])


class RegisterForm(FlaskForm):
    login = StringField('Login', validators=[InputRequired(), Length(min=2, max=15)])
    email = StringField('Email', validators=[InputRequired(), Email(message='Неправильный формат!'), Length(max=50)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=80)])
    password_reply = PasswordField('Password reply', validators=[InputRequired(), Length(min=8, max=80)])
    recaptcha = RecaptchaField(validators=[Recaptcha(message='Please complete the captcha')])

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.login_view = 'main.login'
db = SQLAlchemy()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)

    bootstrap.init_app(app)
    login_manager.init_app(app)
    db.init_app(app)

    from .views import main
    app.register_blueprint(main)

    with app.app_context():
        from app import models, views
        db.create_all()

    return app

app/views.py
from flask import render_template, redirect, flash, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user
from markupsafe import Markup
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from .forms import LoginForm, RegisterForm
from .models import User

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        remember = True if form.remember.data else False

        if user is None or not user.password or not check_password_hash(user.password, form.password.data):
            flash(Markup('Email or password is incorrect, please try again'))
            return redirect(url_for('main.login'))

        login_user(user, remember=remember)
        return redirect(url_for('main.index'))

    return render_template('main/login.html', form=form)


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()  # Проверка есть ли с таким email

        if user:
            flash(Markup('User with this email already exists. Go to <a href="login">login page</a>.'))
            return redirect(url_for('main.signup'))  # Переадресация на эту же страницу, чтобы flash отобразился

        if form.password.data != form.password_reply.data:
            flash('Passwords are different!')
            return redirect(url_for('main.signup'))  # Переадресация на эту же страницу, чтобы flash отобразился

        new_user = User(login=form.login.data,
                        email=form.email.data,
                        password=generate_password_hash(form.password.data))

        db.session.add(new_user)
        db.session.commit()

        return render_template('main/index.html')
    return render_template('main/signup.html', form=form)


@main.route('/profile')
@login_required
def profile():
    return render_template('main/profile.html', name=current_user.login)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/dashboard.html
{% extends "bootstrap/base.html" %}

{% block title %}
This is an example page
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='default-template.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Лабораторная работа №3</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="">Login</a></li>
            <li><a href="">Sign Up</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="index-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
{% endblock %}

app/templates/index.html
{% extends "bootstrap/base.html" %}

{% block title %}
Home
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='default-template.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Laboratory work №3</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>

            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('login') }}">Login</a></li>
            <li><a href="{{ url_for('signup') }}">Sign Up</a></li>
            {% endif %}

            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('profile') }}">Profile</a></li>
            <li><a href="{{ url_for('logout') }}">Logout Up</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="index-template">
        <h1>Это начальная страница</h1>
      </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='login-templates.css')}}">
{% endblock %}

{% block content %}
   <div class="wrapper">
      <form class="form-signin" method="POST" action="/login">
         <h2 class="form-signin-heading">Login</h2>

         {% with messages = get_flashed_messages() %}
            {% if messages %}
               <div class="alert alert-danger" role="alert">
                  {{ messages[0] }}
               </div>
            {% endif %}
         {% endwith %}

         {{ form.hidden_tag() }}
         {{ wtf.form_field(form.email) }}
         {{ wtf.form_field(form.password) }}
         {{ wtf.form_field(form.remember) }}
         {{  wtf.form_field(form.recaptcha)  }}
         <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
         <div class="to-login-btn">Don't have an account? <a href="{{ url_for('signup') }}">Sign Up</a></div>
      </form>
   </div>

{% endblock %}

app/templates/main/index.html
{% extends "bootstrap/base.html" %}

{% block title %}
Home
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='default-template.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Laboratory work №3</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>

            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('main.login') }}">Login</a></li>
            <li><a href="{{ url_for('main.signup') }}">Sign Up</a></li>
            {% endif %}

            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('main.profile') }}">Profile</a></li>
            <li><a href="{{ url_for('main.logout') }}">Logout Up</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="index-template">
        <h1>Это начальная страница</h1>
      </div>
    </div>
{% endblock %}

app/templates/main/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='login-templates.css')}}">
{% endblock %}

{% block content %}
   <div class="wrapper">
      <form class="form-signin" method="POST" action="/login">
         <h2 class="form-signin-heading">Login</h2>

         {% with messages = get_flashed_messages() %}
            {% if messages %}
               <div class="alert alert-danger" role="alert">
                  {{ messages[0] }}
               </div>
            {% endif %}
         {% endwith %}

         {{ form.hidden_tag() }}
         {{ wtf.form_field(form.email) }}
         {{ wtf.form_field(form.password) }}
         {{ wtf.form_field(form.remember) }}
         {{  wtf.form_field(form.recaptcha)  }}
         <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
         <div class="to-login-btn">Don't have an account? <a href="{{ url_for('main.signup') }}">Sign Up</a></div>
      </form>
   </div>

{% endblock %}

app/templates/main/profile.html
{% extends "bootstrap/base.html" %}

{% block title %}
Profile
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='default-template.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Laboratory work №3</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.index') }}">Home</a></li>

            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('main.login') }}">Login</a></li>
            <li><a href="{{ url_for('main.signup') }}">Sign Up</a></li>
            {% endif %}

            {% if current_user.is_authenticated %}
            <li class="active"><a href="{{ url_for('main.profile') }}">Profile</a></li>
            <li><a href="{{ url_for('main.logout') }}">Logout Up</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="index-template">
        <h1>Привет, {{ name }}, это твой профиль</h1>
      </div>
    </div>
{% endblock %}

app/templates/main/signup.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Sign Up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='login-templates.css')}}">
{% endblock %}

{% block content %}
   <div class="wrapper">
      <form class="form-signin" method="POST" action="/signup">
         <h2 class="form-signin-heading">Sign Up</h2>

          {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-danger" role="alert">
                    {{ messages[0] }}
                </div>
            {% endif %}
          {% endwith %}

         {{ form.hidden_tag() }}
         {{ wtf.form_field(form.login) }}
         {{ wtf.form_field(form.email) }}
         {{ wtf.form_field(form.password) }}
         {{ wtf.form_field(form.password_reply) }}
         {{  wtf.form_field(form.recaptcha)  }}
         <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
         <div class="to-login-btn">Have an account? <a href="{{ url_for('main.login') }}">Login</a></div>
      </form>
   </div>

{% endblock %}

app/templates/profile.html
{% extends "bootstrap/base.html" %}

{% block title %}
Profile
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='default-template.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Laboratory work №3</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('index') }}">Home</a></li>

            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('login') }}">Login</a></li>
            <li><a href="{{ url_for('signup') }}">Sign Up</a></li>
            {% endif %}

            {% if current_user.is_authenticated %}
            <li class="active"><a href="{{ url_for('profile') }}">Profile</a></li>
            <li><a href="{{ url_for('logout') }}">Logout Up</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="index-template">
        <h1>Привет, {{ name }}, это твой профиль</h1>
      </div>
    </div>
{% endblock %}

app/templates/signup.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Sign Up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='login-templates.css')}}">
{% endblock %}

{% block content %}
   <div class="wrapper">
      <form class="form-signin" method="POST" action="/signup">
         <h2 class="form-signin-heading">Sign Up</h2>

          {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-danger" role="alert">
                    {{ messages[0] }}
                </div>
            {% endif %}
          {% endwith %}

         {{ form.hidden_tag() }}
         {{ wtf.form_field(form.login) }}
         {{ wtf.form_field(form.email) }}
         {{ wtf.form_field(form.password) }}
         {{ wtf.form_field(form.password_reply) }}
         {{  wtf.form_field(form.recaptcha)  }}
         <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
         <div class="to-login-btn">Have an account? <a href="{{ url_for('login') }}">Login</a></div>
      </form>
   </div>

{% endblock %}